# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate input-sys

# ---------------------------------------------------------------------------
# Forked/adapted from Fedora's rawhide dist-git for dank-ws-copr:
#   https://src.fedoraproject.org/rpms/rust-input-sys/raw/rawhide/f/rust-input-sys.spec
# Adapted 2026-09-24. Not branched to epel9/epel10 (404 on both). Needed by rust-input
# (specs/rust-input/), itself needed by mir's Rust input-evdev-rs component - discovered via a
# real failed mock build of rust-input (it needs input-sys transitively, which wasn't packaged).
# Release: %%autorelease -> 1%%{?dist}; %%changelog: manual (rpmautospec n/a on el10).
# STATUS: not yet mock-built.
# ---------------------------------------------------------------------------

Name:           rust-input-sys
Version:        1.19.0
Release:        1%{?dist}
Summary:        Bindgen generated unsafe libinput wrapper

License:        MIT
URL:            https://crates.io/crates/input-sys
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * regenerate bindings during the build by default
Patch:          input-sys-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(libudev)

%global _description %{expand:
Bindgen generated unsafe libinput wrapper.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput)
Requires:       pkgconfig(libudev)

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_11-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.11

%description -n %{name}+libinput_1_11-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_11" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_11-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_14-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.14

%description -n %{name}+libinput_1_14-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_14" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_14-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_15-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.15

%description -n %{name}+libinput_1_15-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_15" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_15-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_19-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.19

%description -n %{name}+libinput_1_19-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_19" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_19-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_21-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.21

%description -n %{name}+libinput_1_21-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_21" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_21-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_23-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.23

%description -n %{name}+libinput_1_23-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_23" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_23-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_26-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.26

%description -n %{name}+libinput_1_26-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_26" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_26-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_27-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.27

%description -n %{name}+libinput_1_27-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_27" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_27-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_28-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.28

%description -n %{name}+libinput_1_28-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_28" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_28-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_29-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.29

%description -n %{name}+libinput_1_29-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_29" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_29-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_30-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(libinput) >= 1.30

%description -n %{name}+libinput_1_30-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_30" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_30-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+proc-macro2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+proc-macro2-devel %{_description}

This package contains library source intended for building other packages which
use the "proc-macro2" feature of the "%{crate}" crate.

%files       -n %{name}+proc-macro2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+regex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-devel %{_description}

This package contains library source intended for building other packages which
use the "regex" feature of the "%{crate}" crate.

%files       -n %{name}+regex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+update_bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+update_bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "update_bindings" feature of the "%{crate}" crate.

%files       -n %{name}+update_bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "use_bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+use_bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Oct 05 2026 Karl Fischer <karl@obsidian.co.za> - 1.19.0-1
- Update to 1.19.0; add libinput_1_23..libinput_1_30 feature subpackages
- Refresh metadata patch (upstream now uses bindgen 0.72, only the
  regenerate-bindings-by-default change remains)

* Thu Sep 24 2026 Karl Fischer <karl@obsidian.co.za> - 1.18.0-1
- Initial dank-ws-copr package, adapted from Fedora rawhide dist-git spec
