# ---------------------------------------------------------------------------
# Forked/adapted from Fedora's rawhide dist-git for dank-ws-copr:
#   https://src.fedoraproject.org/rpms/rust-enquote/raw/rawhide/f/rust-enquote.spec
# Adapted 2026-09-24. Not branched to epel9/epel10 in Fedora (checked: HTTP 404 on both) - the
# other of two missing crate dependencies blocking `greetd` (specs/greetd/greetd.spec, SETUP.md
# Step 11). Same `rust-packaging` -> `cargo-rpm-macros` satisfaction as rust-pam-sys.
#
# Changes vs. upstream Fedora spec:
#   - Release: %%autorelease -> plain 1%%{?dist} (rpmautospec not available on el10).
#   - %%changelog: %%autochangelog -> manual initial entry.
# ---------------------------------------------------------------------------

# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate enquote

Name:           rust-enquote
Version:        1.1.0
Release:        1%{?dist}
Summary:        Quotes and unquotes strings

License:        Unlicense
URL:            https://crates.io/crates/enquote
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Quotes and unquotes strings.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%doc %{crate_instdir}/readme.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Sep 24 2026 Karl Fischer <karl@obsidian.co.za> - 1.1.0-1
- Initial dank-ws-copr package, adapted from Fedora rawhide dist-git spec
- Replaced %%autorelease/%%autochangelog (rpmautospec) with static Release/changelog
