# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate input

# ---------------------------------------------------------------------------
# Forked/adapted from Fedora's rawhide dist-git for dank-ws-copr:
#   https://src.fedoraproject.org/rpms/rust-input/raw/rawhide/f/rust-input.spec
# Adapted 2026-09-24. Not branched to epel9/epel10 (404 on both). Needed by `mir`'s Rust
# input-evdev-rs component (Cargo.lock wants input >=0.8.3, <0.11.0, both default and
# libinput_1_19 features - 0.9.1 satisfies).
# Release: %%autorelease -> 1%%{?dist}; %%changelog: manual (rpmautospec n/a on el10).
# STATUS: not yet mock-built.
# ---------------------------------------------------------------------------

Name:           rust-input
Version:        0.9.1
Release:        1%{?dist}
Summary:        Libinput bindings for rust

License:        MIT
URL:            https://crates.io/crates/input
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Libinput bindings for rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_11-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libinput_1_11-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_11" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_11-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libinput_1_14-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_14" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_14-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_15-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libinput_1_15-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_15" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_15-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_19-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libinput_1_19-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_19" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_19-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libinput_1_21-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libinput_1_21-devel %{_description}

This package contains library source intended for building other packages which
use the "libinput_1_21" feature of the "%{crate}" crate.

%files       -n %{name}+libinput_1_21-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-devel %{_description}

This package contains library source intended for building other packages which
use the "log" feature of the "%{crate}" crate.

%files       -n %{name}+log-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+udev-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+udev-devel %{_description}

This package contains library source intended for building other packages which
use the "udev" feature of the "%{crate}" crate.

%files       -n %{name}+udev-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "use_bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+use_bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Sep 24 2026 Karl Fischer <karl@obsidian.co.za> - 0.9.1-1
- Initial dank-ws-copr package, adapted from Fedora rawhide dist-git spec
