# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate calloop

# ---------------------------------------------------------------------------
# Forked/adapted from Fedora's rawhide dist-git for dank-ws-copr:
#   https://src.fedoraproject.org/rpms/rust-calloop/raw/rawhide/f/rust-calloop.spec
# Adapted 2026-09-24. Branched to epel9 but not epel10 (checked el10 - 404). Needed by `mir`'s
# Rust input-evdev-rs component (Cargo.lock wants calloop >=0.10.0, <0.15.0 - 0.14.4 satisfies).
# Release: %%autorelease -> 1%%{?dist}; %%changelog: manual (rpmautospec n/a on el10).
# STATUS: not yet mock-built.
# ---------------------------------------------------------------------------

Name:           rust-calloop
Version:        0.14.4
Release:        1%{?dist}
Summary:        Callback-based event loop

License:        MIT
URL:            https://crates.io/crates/calloop
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop unused, benchmark-only criterion dev-dependency
Patch:          calloop-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A callback-based event loop.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-task-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-task-devel %{_description}

This package contains library source intended for building other packages which
use the "async-task" feature of the "%{crate}" crate.

%files       -n %{name}+async-task-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+block_on-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+block_on-devel %{_description}

This package contains library source intended for building other packages which
use the "block_on" feature of the "%{crate}" crate.

%files       -n %{name}+block_on-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+executor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+executor-devel %{_description}

This package contains library source intended for building other packages which
use the "executor" feature of the "%{crate}" crate.

%files       -n %{name}+executor-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-core" feature of the "%{crate}" crate.

%files       -n %{name}+futures-core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-io-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-io-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-io" feature of the "%{crate}" crate.

%files       -n %{name}+futures-io-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nix-devel %{_description}

This package contains library source intended for building other packages which
use the "nix" feature of the "%{crate}" crate.

%files       -n %{name}+nix-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pin-utils-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pin-utils-devel %{_description}

This package contains library source intended for building other packages which
use the "pin-utils" feature of the "%{crate}" crate.

%files       -n %{name}+pin-utils-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+signals-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+signals-devel %{_description}

This package contains library source intended for building other packages which
use the "signals" feature of the "%{crate}" crate.

%files       -n %{name}+signals-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stream-devel %{_description}

This package contains library source intended for building other packages which
use the "stream" feature of the "%{crate}" crate.

%files       -n %{name}+stream-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Sep 24 2026 Karl Fischer <karl@obsidian.co.za> - 0.14.4-1
- Initial dank-ws-copr package, adapted from Fedora rawhide dist-git spec
