# ---------------------------------------------------------------------------
# Forked/adapted from Fedora's rawhide dist-git for dank-ws-copr:
#   https://src.fedoraproject.org/rpms/rust-greetd_ipc/raw/rawhide/f/rust-greetd_ipc.spec
# Adapted 2026-09-24. Not branched to epel9/epel10 (checked: 404 on both). Needed because
# `greetd`'s own Cargo.toml uses a local *path* dependency on `greetd_ipc` (same source tree), but
# `%%cargo_generate_buildrequires` still emits an external `crate(greetd_ipc/...)` BuildRequires for
# it regardless - discovered via a real failed mock build (SETUP.md Step 11). Fedora's own greetd
# build satisfies this the same way: a separate `rust-greetd_ipc` crate package (it's independently
# published on crates.io under that name too, hence rust2rpm can auto-generate a spec for it).
#
# Changes vs. upstream Fedora spec:
#   - Release: %%autorelease -> plain 1%%{?dist} (rpmautospec not available on el10).
#   - %%changelog: %%autochangelog -> manual initial entry.
# ---------------------------------------------------------------------------

# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate greetd_ipc

Name:           rust-greetd_ipc
Version:        0.10.3
Release:        1%{?dist}
Summary:        Implementation of the greetd IPC protocol

License:        GPL-3.0-only
URL:            https://crates.io/crates/greetd_ipc
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An implementation of the greetd IPC protocol.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-trait-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-trait-devel %{_description}

This package contains library source intended for building other packages which
use the "async-trait" feature of the "%{crate}" crate.

%files       -n %{name}+async-trait-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+codec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+codec-devel %{_description}

This package contains library source intended for building other packages which
use the "codec" feature of the "%{crate}" crate.

%files       -n %{name}+codec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sync-codec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sync-codec-devel %{_description}

This package contains library source intended for building other packages which
use the "sync-codec" feature of the "%{crate}" crate.

%files       -n %{name}+sync-codec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+thiserror-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+thiserror-devel %{_description}

This package contains library source intended for building other packages which
use the "thiserror" feature of the "%{crate}" crate.

%files       -n %{name}+thiserror-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-codec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-codec-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-codec" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-codec-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Sep 24 2026 Karl Fischer <karl@obsidian.co.za> - 0.10.3-1
- Initial dank-ws-copr package, adapted from Fedora rawhide dist-git spec
- Replaced %%autorelease/%%autochangelog (rpmautospec) with static Release/changelog
