# ---------------------------------------------------------------------------
# Forked/adapted from Fedora's rawhide dist-git for dank-ws-copr:
#   https://src.fedoraproject.org/rpms/rust-pam-sys/raw/rawhide/f/rust-pam-sys.spec
# Adapted 2026-09-24. Not branched to epel9/epel10 in Fedora (checked: HTTP 404 on both) - one of
# two missing crate dependencies blocking `greetd` (specs/greetd/greetd.spec, SETUP.md Step 11).
# `rust-packaging` (this spec's only real BuildRequires) is satisfied on el10 by EPEL's
# `cargo-rpm-macros`, which explicitly `Provides: rust-packaging` (verified: `rpm -q --provides
# cargo-rpm-macros`) - otherwise unchanged from upstream besides the release/changelog swap below.
#
# Changes vs. upstream Fedora spec:
#   - Release: %%autorelease -> plain 1%%{?dist} (rpmautospec not available on el10).
#   - %%changelog: %%autochangelog -> manual initial entry.
# ---------------------------------------------------------------------------

# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate pam-sys

Name:           rust-pam-sys
Version:        0.5.6
Release:        1%{?dist}
Summary:        FFI wrappers for the Linux Pluggable Authentication Modules (PAM)

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/pam-sys
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
FFI wrappers for the Linux Pluggable Authentication Modules (PAM).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pam-devel

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires
echo 'pam-devel'

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Sep 24 2026 Karl Fischer <karl@obsidian.co.za> - 0.5.6-1
- Initial dank-ws-copr package, adapted from Fedora rawhide dist-git spec
- Replaced %%autorelease/%%autochangelog (rpmautospec) with static Release/changelog
