# ---------------------------------------------------------------------------
# Forked/adapted from Fedora's rawhide dist-git for dank-ws-copr:
#   https://src.fedoraproject.org/rpms/rust-rpassword5/raw/rawhide/f/rust-rpassword5.spec
# Adapted 2026-09-24. Already branched to epel9 (HTTP 200) but not epel10 yet (404) - just needs
# the same branch request repeated, an established Fedora pattern, not exotic. Needed because
# `greetd`'s Cargo.lock pins `rpassword = 5.0.1` exactly, while el10's only available
# `rust-rpassword` is 7.5.4 (a semver-incompatible major bump) - discovered via a real failed mock
# build (SETUP.md Step 11). `rust-rpassword5` is Fedora's own side-by-side-installable compat
# package name for exactly this "an old major version is still needed" situation.
#
# Changes vs. upstream Fedora spec:
#   - Release: %%autorelease -> plain 1%%{?dist} (rpmautospec not available on el10).
#   - %%changelog: %%autochangelog -> manual initial entry.
# ---------------------------------------------------------------------------

# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate rpassword

Name:           rust-rpassword5
Version:        5.0.1
Release:        1%{?dist}
Summary:        Read passwords in console applications

License:        Apache-2.0
URL:            https://crates.io/crates/rpassword
Source:         %{crates_source}
# Automatically generated patch to strip foreign dependencies
Patch:          rpassword-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Read passwords in console applications.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Sep 24 2026 Karl Fischer <karl@obsidian.co.za> - 5.0.1-1
- Initial dank-ws-copr package, adapted from Fedora rawhide dist-git spec
- Replaced %%autorelease/%%autochangelog (rpmautospec) with static Release/changelog
